#!/usr/bin/env python

import tempfile, sys, os, subprocess, shutil

def die(msg):
  print(msg)
  exit(1)

to_rename = sys.argv[1:]

if not to_rename:
  die("usage: edmv source_file ...")

editor = os.environ.get("EDMV_EDITOR") or os.environ.get('EDITOR') or 'vi'

with tempfile.NamedTemporaryFile(prefix="edmv", delete=False) as f:
  path = f.name
  f.write("\n".join(to_rename).encode('utf-8'))

code = subprocess.call("%s %s" % (editor, path), shell=True)

if code != 0:
  die("call to editor failed! giving up.")

with open(path) as f:
  edited = f.readlines()

os.remove(path)

if len(edited) != len(to_rename):
  die("line count mismatch. giving up")

for i in range(len(to_rename)):
  pre  = to_rename[i].strip()
  post = edited[i].strip()
  print(" ".join([pre, "->", post]))
  shutil.move(pre, post)
